/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-09-13 15:31:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.debate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class debate_005fchanban_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("utf-8");
	String title = "찬반 토론";

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!-- Post Start -->\r\n");
      out.write("\t\t\t<div class=\"col-md-15\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 page-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 content-page \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Default panel contents -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<u>찬반토론</u>\r\n");
      out.write("\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"margin-bottom-50\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-lg\">토론방\r\n");
      out.write("\t\t\t\t\t\t\t\t\t만들기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"testimonials\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"active item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img alt=\"\" src=\"images/testimonial/1.png\" class=\"pull-left\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"z-index: 10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<blockquote>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>한국에서 대마초는 마약류로 분류된다. 대마초를 흡입하지 않아도 그것을 소지하는 것만으로\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t처벌받을 만큼 중범죄에 해당된다. 하지만 다른 마약과 달리 그 효과와 관련해서 논란이 있다. 대마초\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t흡입이 인체에 얼마나 유해한지, 나아가 타인에게 피해를 줄 것인지에 대해 명확히 규정되지 않은 것이다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t실제로 대마초를 마약으로 규정하지 않는 국가들이 있다. 우루과이는 2013년 세계 최초로 오락용 대마초\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t흡입을 합법화했고, 2018년 캐나다 역시 같은 법안을 통과시켰다. 체코는 의료용 대마초만을 합법화했지만\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t실질적으로 그 외의 이유로 대마초를 사용했다고 해서 처벌하진 않는다. 네덜란드에서도 의료 목적이라면 의사\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t처방을 받고 대마초를 구매할 수 있다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</blockquote>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"testimonials\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"active item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img alt=\"\" src=\"images/testimonial/1.png\" class=\"pull-left\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"z-index: 10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<blockquote>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>1957년 소련은 세계최초로 인공위성을 개발하여 우주로 쏘아 올리며, ‘우주 강국’이라는\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t명성을 얻게 되었다. 이에 충격을 받은 미국은 미국항공우주국(NASA)을 설립하여 적극적으로 우주개발에\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t나섰고, 존 F. 캐네디는 달 착륙 계획을 수립했다. 그렇게 1969년 7월, 3명의 우주비행사(닐\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t암스트롱, 에드윈 올드린 주니어, 마이클 콜린스)가 탑승한 아폴로 11호는 달에 착륙했다. NASA를\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t통해 약 5억 명의 사람들이 이 역사적인 장면을 목격했다. 그동안 신화나 상상으로만 가야 했던 달의\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t실체가 아폴로 11호의 우주탐험으로 드러난 것이다. 달 착륙 성공은 국제우주정거장과 인공위성의 개발 등\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t인류 과학이 진보하는 역사적인 사건으로 기록되었다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</blockquote>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"testimonials\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"active item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img alt=\"\" src=\"images/testimonial/1.png\" class=\"pull-left\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"z-index: 10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<blockquote>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>2006년 미국의 사회운동가인 타라나 버크는 소수인종 여성과 아동을 위해 그들의 피해 사실을\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t밝히고 독려하며, 피해자들의 연대를 이루는 운동을 시작한다. 이 운동이 궤도에 진입한 것은 2017년\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t영화 제작자 하비 와인스타인의 성폭력을 할리우드의 배우들이 폭로하면서부터였다. 그녀들은 SNS의\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t해시태그(#MeToo)를 이용하여 사람들에게 자신들의 상처를 알렸다. 이제 더 이상 피해 사실을 숨기며\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t침묵하지 않겠다는 뜻에서 시작된 것이 미투운동이다. 한국의 미투운동은 2018년 한 여성 검사의 폭로로\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t시작되었다. 이 검사는 자신이 당한 성폭력을 검찰이 덮으려고 하자, 검찰 내부 통신망과 언론을 통해\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t고발했다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</blockquote>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Post End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
