/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-09-27 14:44:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.movie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class movie_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	String title = "영화 목록";
	String resultPage = request.getParameter("resultPage");
	if (resultPage == null || resultPage.length() == 0) {
		resultPage = "1";
	}
	String sort = request.getParameter("sort");
	if (sort == null || sort.length() == 0) {
		sort = "vote_count";
	}

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h3>\r\n");
      out.write("\t\t");
      out.print(title);
      out.write("\r\n");
      out.write("\t\t<small class=\"text-muted\">Movie List</small>\r\n");
      out.write("\t</h3>\r\n");
      out.write("\t<p class=\"lead\"></p>\r\n");
      out.write("\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary\">장르</button>\r\n");
      out.write("\t\t<div class=\"btn-group show\" role=\"group\">\r\n");
      out.write("\t\t\t<button id=\"selectGenre\" type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\"></button>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"selectGenre\" x-placement=\"bottom-start\" style=\"position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 48px, 0px);\">\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">전체</a> \r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">액션</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">모험</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">애니메이션</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">코미디</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">범죄</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">다큐멘터리</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">드라마</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">가족</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">판타지</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">역사</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">공포</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">음악</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">미스터리</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">로맨스</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">SF</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">TV 영화</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">스릴러</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">전쟁</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">서부</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary\">정렬</button>\r\n");
      out.write("\t\t<div class=\"btn-group show\" role=\"group\">\r\n");
      out.write("\t\t\t<button id=\"selectSort\" type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\"></button>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"btnGroupDrop2\" x-placement=\"bottom-start\" style=\"position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 48px, 0px);\">\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"movie_list.jsp?resultPage=1&sort=vote_count\">인기순</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"movie_list.jsp?resultPage=1&sort=release_date\">최근 개봉순</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"movie_list.jsp?resultPage=1&sort=revenue\">최고 흥행순</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Pagination -->\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">&laquo;</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"page-item active\"><a class=\"page-link\" href=\"movie_list.jsp?resultPage=1&sort=vote_count\">1</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"movie_list.jsp?resultPage=2&sort=vote_count\">2</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"movie_list.jsp?resultPage=3&sort=vote_count\">3</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"movie_list.jsp?resultPage=4&sort=vote_count\">4</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"movie_list.jsp?resultPage=5&sort=vote_count\">5</a></li>\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">&raquo;</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tvar page = '");
      out.print(resultPage);
      out.write("';\r\n");
      out.write("\tvar sort = '");
      out.print(sort);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar settings = {\r\n");
      out.write("\t  \tasync: true,\r\n");
      out.write("\t  \tcrossDomain: true,\r\n");
      out.write("\t  \turl: 'https://api.themoviedb.org/3/discover/movie',\r\n");
      out.write("\t\tmethod: 'GET',\r\n");
      out.write("\t  \tdata: {\r\n");
      out.write("\t\t\t'page': page,\r\n");
      out.write("\t\t  \t'include_video': 'false',\r\n");
      out.write("\t\t  \t'include_adult': 'false',\r\n");
      out.write("\t\t  \t'sort_by': sort+'.desc',\r\n");
      out.write("\t\t  \t'region': 'KR',\r\n");
      out.write("\t\t  \t'language': 'ko-KR',\r\n");
      out.write("\t\t  \t'api_key': '9dd279523f7113a4103a8f1e9ef6abe3'\r\n");
      out.write("\t  \t},\r\n");
      out.write("\t  \tdataType: 'json',\r\n");
      out.write("\t  \theaders: {}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$.ajax(settings).done(function (response) {\r\n");
      out.write("\t\tconsole.log(response);\r\n");
      out.write("  \t\t$('.lead').html('총 '+response.total_results+'개의 작품 검색');\r\n");
      out.write("  \t\tvar rs = [];\r\n");
      out.write("  \t\tvar hoverList = new Array();\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\tvar settings2 = {\r\n");
      out.write("\t\t  \"async\": true,\r\n");
      out.write("\t\t  \"crossDomain\": true,\r\n");
      out.write("\t\t  \"url\": \"https://api.themoviedb.org/3/genre/movie/list?language=ko-KR&api_key=9dd279523f7113a4103a8f1e9ef6abe3\",\r\n");
      out.write("\t\t  \"method\": \"GET\",\r\n");
      out.write("\t\t  \"headers\": {},\r\n");
      out.write("\t\t  \"data\": \"{}\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax(settings2).done(function (response2) {\r\n");
      out.write("\t\t  console.log(response2);\r\n");
      out.write("\t\t});\r\n");
      out.write("  \r\n");
      out.write("  \t\tfor(var i=0; i<response['results'].length; i++) {\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  /* \t\t\tvar data = new Object();\r\n");
      out.write("  \t\t\tdata.index = i;\r\n");
      out.write("  \t\t\tdata.overview = response['results'][i]['overview'];\r\n");
      out.write("  \t\t\tdata.popularity = response['results'][i]['popularity'];\r\n");
      out.write("  \t\t\thoverList.push(data); */\r\n");
      out.write("  \t\t\t  \t\t\t\r\n");
      out.write("  \t\t\trs.push('<div class=\"card mb-3 col-lg-3\">');\r\n");
      out.write("  \t\t\trs.push('<h4 class=\"card-header\">'+response['results'][i]['title']+'</h4>');\r\n");
      out.write("  \t\t\tif(response['results'][i]['poster_path'] == null) {\r\n");
      out.write("  \t\t  \t\trs.push('<a href=\"movie_detail.jsp?id='+response['results'][i]['id']+'\" class=\"hvr-fade\"><img style=\"width: 100%; display: block;\" src=\"https://via.placeholder.com/350x500?text=dont+find+poster\" alt=\"Card image\"></a>');\r\n");
      out.write("  \t\t\t} else {\r\n");
      out.write("  \t\t  \t\trs.push('<a href=\"movie_detail.jsp?id='+response['results'][i]['id']+'\" class=\"hvr-fade\"><img class=\"hvr-fade\" style=\"width: 100%; display: block;\" src=\"https://image.tmdb.org/t/p/original'+response['results'][i]['poster_path']+'\" alt=\"Card image\"></a>');\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t  \trs.push('<ul class=\"list-group list-group-flush\">');\r\n");
      out.write("\t\t\trs.push('<li class=\"list-group-item\" id=\"genre\">장르 '+response['results'][i]['genre_ids']+'</li>');\r\n");
      out.write("\t\t\trs.push('<li class=\"list-group-item\">개봉일 '+response['results'][i]['release_date']+'</li>');\r\n");
      out.write("\t\t\trs.push('</ul>');\r\n");
      out.write("\t\t\trs.push('<div class=\"card-body\">');\r\n");
      out.write("\t\t\trs.push('<a href=\"#\" class=\"card-link\">예매하기</a>');\r\n");
      out.write("\t\t\trs.push('<a href=\"movie_detail.jsp?id='+response['results'][i]['id']+'\" class=\"card-link\">상세보기</a>');\r\n");
      out.write("\t\t\trs.push('</div>');\r\n");
      out.write("\t\t\trs.push('</div>');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* $.each(genresArray, function(index, item) {\r\n");
      out.write("\t\t\t\t$('#genre').html(item.join(','));\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\r\n");
      out.write("  \t  \t\t$('.row').html(rs.join(''));\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\t\r\n");
      out.write("/*   \t\tvar jsonData = JSON.stringify(hoverList);\r\n");
      out.write("  \t\tconsole.log(jsonData); */\r\n");
      out.write("\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t/*\r\n");
      out.write("\t\t.pagination : 페이징 태그가 그려질 div\r\n");
      out.write("\t\t#pageIndex : 현재 페이지 위치 저장\r\n");
      out.write("\t\trecordCount : 페이지당 레코드 수\r\n");
      out.write("\t\ttotal_pages : 전체 페이지 수\r\n");
      out.write("\t\ttotl_results : 전체 결과 수\r\n");
      out.write("\t\teventName : 페이징 하단의 숫자 등의 버튼이 클릭되었을 때 호출될 함수 이름\r\n");
      out.write("  \t\t*/\r\n");
      out.write("  \t\tvar pageIndex = null;\r\n");
      out.write("  \t\tvar eventName = null;\r\n");
      out.write("  \t\t$('li.page-item').click(function() {\r\n");
      out.write("  \t  \t\tvar pagination = $('.pagination'); //그려질 div\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
