/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-09-22 12:57:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.text.SimpleDateFormat;

public final class movie_005fquiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	String title = "영화 퀴즈";
	String userid = request.getParameter("userid");

      out.write('\r');
      out.write('\n');

	SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일");
	String today = sdf.format(new java.util.Date());

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h3>\r\n");
      out.write("\t\t");
      out.print(title);
      out.write("\r\n");
      out.write("\t\t<small class=\"text-muted\">Movie Quiz</small>\r\n");
      out.write("\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<form name=\"movieQuiz\" method=\"post\" action=\"movie_quiz_pro.jsp\">\r\n");
      out.write("\t\t\t<p>");
      out.print(today );
      out.write("</p>\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>회차정보</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\"><input type=\"text\" size=\"3\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"episode\" placeholder=\"회차\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\">회</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>문제 1.</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\"><input type=\"text\" size=\"50\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" name=\"question1\" placeholder=\"문제를 입력하세요.\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>정답</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio1\" value=\"1\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer1\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio1\" value=\"2\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer2\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio1\" value=\"3\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer3\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio1\" value=\"4\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer4\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>문제 2.</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" size=\"50\" class=\"form-control\" name=\"question2\" placeholder=\"문제를 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>정답</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio2\" value=\"1\" disabled=\"disabled\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer5\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio2\" value=\"2\" disabled=\"disabled\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer6\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio2\" value=\"3\" disabled=\"disabled\">  \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer7\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio2\" value=\"4\" disabled=\"disabled\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer8\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>문제 3.</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" size=\"50\" class=\"form-control\" name=\"question3\" placeholder=\"문제를 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>정답</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio3\" value=\"1\" disabled=\"disabled\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer9\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio3\" value=\"2\" disabled=\"disabled\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer10\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio3\" value=\"3\" disabled=\"disabled\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer11\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"radio3\" value=\"4\" disabled=\"disabled\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"answer12\" placeholder=\"답을 입력하세요.\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-offset-4 col-sm-2 col-xs-4\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\">제출하기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
