/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-09-22 11:56:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class movie_005fissue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	request.setCharacterEncoding("utf-8");
	String title = "영화 이슈";

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h3>\r\n");
      out.write("\t\t");
      out.print(title );
      out.write("\r\n");
      out.write("\t\t<small class=\"text-muted\">Movie Issue</small>\r\n");
      out.write("\t</h3>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("\t\t\t\t<a href=\"https://www.msn.com/ko-kr/entertainment/movies/‘봄이가도’-세월호-4년-그래도-잊지-않겠다는-약속개봉day/ar-BBNggAE\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"https://img-s-msn-com.akamaized.net/tenant/amp/entityid/BBNgnGZ.img?h=385&w=270&m=6&q=60&o=f&l=f&x=282&y=465\" alt=\"Card image cap\" >\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<a href=\"https://www.msn.com/ko-kr/entertainment/movies/‘봄이가도’-세월호-4년-그래도-잊지-않겠다는-약속개봉day/ar-BBNggAE\" class=\"card-text\">‘봄이가도’ 세월호 4년, 그래도 잊지 않겠다는 약속[개봉DAY]</a>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNgdEQ?ocid=st\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"https://img-s-msn-com.akamaized.net/tenant/amp/entityid/BBNgdEP.img?h=387&w=270&m=6&q=60&o=f&l=f&x=394&y=291\" alt=\"Card image cap\" >\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNgdEQ?ocid=st\" class=\"card-text\">260만 돌파 ‘너의 결혼식’ 2018 로맨스 영화 흥행 1위[박스오피스]</a>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNgvD3?ocid=st\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"https://c-6rtwjumjzx7877x24nrl-x78-rx78s-htrx2efpfrfnejix2esjy.g01.msn.com/g00/3_c-6bbb.rx78s.htr_/c-6RTWJUMJZX77x24myyux78x3ax2fx2fnrl-x78-rx78s-htr.fpfrfneji.sjyx2fyjsfsyx2ffrux2fjsynydnix2fGGSlvmA.nrlx3fmx3d808x26bx3d725x26rx3d1x26vx3d15x26tx3dkx26qx3dkx26cx3d879x26dx3d709x26n65h.rfwpx3dnrflj_$/$/$/$/$\" alt=\"Card image cap\" >\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNgvD3?ocid=st\" class=\"card-text\">‘암수살인’ 감독 “낯설고 생소한 단어를 소재로 한 이유는..”</a>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNg82I?ocid=st\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"https://img-s-msn-com.akamaized.net/tenant/amp/entityid/BBNg82D.img?h=338&w=270&m=6&q=60&o=f&l=f&x=277&y=103\" alt=\"Card image cap\" >\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNg82I?ocid=st\" class=\"card-text\">‘협상’ 손예진 “감옥같았던 촬영장, 심리적 압박 컸다”(인터뷰)</a>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNfOxf?ocid=st\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"https://c-6rtwjumjzx7877x24nrl-x78-rx78s-htrx2efpfrfnejix2esjy.g01.msn.com/g00/3_c-6bbb.rx78s.htr_/c-6RTWJUMJZX77x24myyux78x3ax2fx2fnrl-x78-rx78s-htr.fpfrfneji.sjyx2fyjsfsyx2ffrux2fjsynydnix2fGGSkZlp.nrlx3fmx3d839x26bx3d725x26rx3d1x26vx3d15x26tx3dkx26qx3dkx26cx3d750x26dx3d662x26n65h.rfwpx3dnrflj_$/$/$/$/$\" alt=\"Card image cap\" >\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNfOxf?ocid=st\" class=\"card-text\">박터지는 추석 극장가, ‘협상’ 유일한 현대극 통할까[무비와치]</a>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNcT1T?ocid=st\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"https://img-s-msn-com.akamaized.net/tenant/amp/entityid/BBNcVBv.img?h=416&w=799&m=6&q=60&u=t&o=f&l=f\" alt=\"Card image cap\" >\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://a.msn.com/07/ko-kr/BBNcT1T?ocid=st\">‘더 프레데터’ 액션X스케일X캐릭터 관람포인트 셋</a>\r\n");
      out.write("\t\t\t  \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<a class=\"btn btn-sm btn-outline-secondary\" href=\"writeForm.jsp?board_id=5&article_writer=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" role=\"button\" >글쓰기</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
