/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-09-26 16:18:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import moviedam.board.ArticleDBBean;
import moviedam.board.RestaurantDBBean;
import moviedam.board.PreviewDBBean;
import moviedam.board.IssueDBBean;
import java.sql.Timestamp;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import com.oreilly.servlet.MultipartRequest;
import java.util.*;
import java.io.*;

public final class writePro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("moviedam.board.RestaurantDBBean");
    _jspx_imports_classes.add("moviedam.board.IssueDBBean");
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.DefaultFileRenamePolicy");
    _jspx_imports_classes.add("moviedam.board.PreviewDBBean");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("moviedam.board.ArticleDBBean");
    _jspx_imports_classes.add("com.oreilly.servlet.MultipartRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 request.setCharacterEncoding("utf-8"); 
      out.write('\n');
	
	MultipartRequest multi = null;
	//게시판 구분
	int board_id = Integer.parseInt(request.getParameter("board_id"));
	String uploadPath = "";
	String fileName = ""; //서버에 저장된 파일 이름
	if (board_id == 1) {
		uploadPath = getServletContext().getRealPath("/imageFolder/free_board"); //파일을 저장할 서버의 경로
	} else if (board_id == 2) {
		uploadPath = getServletContext().getRealPath("/imageFolder/cinema_restaurant");
	} else if (board_id == 4) {
		uploadPath = getServletContext().getRealPath("/imageFolder/movie_preview");
	} else if (board_id == 5) {
		uploadPath = getServletContext().getRealPath("/imageFolder/movie_issue");
	}
	int maxSize = 5*1024*1024; //5MB
	
	try {
		//파일업로드 (request, 파일 저장경로, 용량, 인코딩타입, 중복 파일명에 대한 기본 정책)
		multi = new MultipartRequest(request, uploadPath, maxSize, "utf-8", new DefaultFileRenamePolicy());
	
		//파일 정보 가져와 출력
		Enumeration <?> files = multi.getFileNames();
		while(files.hasMoreElements()) {
			String name = (String)files.nextElement();
			fileName = multi.getFilesystemName(name);
		}
		
	} catch(Exception e) {
		e.printStackTrace();
	}

      out.write('\n');
      out.write('\n');
      moviedam.board.ArticleDataBean article = null;
      article = (moviedam.board.ArticleDataBean) _jspx_page_context.getAttribute("article", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (article == null){
        article = new moviedam.board.ArticleDataBean();
        _jspx_page_context.setAttribute("article", article, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\n");
        out.write("   ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("article"), request);
        out.write('\n');
      }
      out.write('\n');
      moviedam.board.RestaurantDataBean restaurant = null;
      restaurant = (moviedam.board.RestaurantDataBean) _jspx_page_context.getAttribute("restaurant", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (restaurant == null){
        restaurant = new moviedam.board.RestaurantDataBean();
        _jspx_page_context.setAttribute("restaurant", restaurant, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\n");
        out.write("   ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("restaurant"), request);
        out.write('\n');
      }
      out.write('\n');
      moviedam.board.PreviewDataBean preview = null;
      preview = (moviedam.board.PreviewDataBean) _jspx_page_context.getAttribute("preview", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (preview == null){
        preview = new moviedam.board.PreviewDataBean();
        _jspx_page_context.setAttribute("preview", preview, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\n");
        out.write("   ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("preview"), request);
        out.write('\n');
      }
      out.write('\n');
      moviedam.board.IssueDataBean issue = null;
      issue = (moviedam.board.IssueDataBean) _jspx_page_context.getAttribute("issue", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (issue == null){
        issue = new moviedam.board.IssueDataBean();
        _jspx_page_context.setAttribute("issue", issue, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\n");
        out.write("   ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("issue"), request);
        out.write('\n');
      }
      out.write('\n');
      out.write(' ');
      out.write('\n');
	
	//가져올 데이터
	String article_writer = multi.getParameter("article_writer");
	String article_title = multi.getParameter("article_title");
	Timestamp reg_date = new Timestamp(System.currentTimeMillis());

	if(board_id == 1) { //자유게시판
		String category = multi.getParameter("category");
		String article_content = multi.getParameter("article_content");

	    article.setArticle_writer(article_writer);
	    article.setArticle_title(article_title);
	    article.setArticle_content(article_content);
	    article.setReg_date(reg_date);
	    article.setArticle_file(fileName);
	    article.setCategory(category);
	    
	    ArticleDBBean article_db = ArticleDBBean.getInstance();
	    article_db.insertArticle(article); 
	    response.sendRedirect("./free_board.jsp?pageNum=1&category=all");
	} else if(board_id == 2) { //맛집게시판
		String search_loc = multi.getParameter("search_loc");
		String article_content = multi.getParameter("article_content");
	
		restaurant.setArticle_writer(article_writer);
		restaurant.setArticle_title(article_title);
		restaurant.setArticle_content(article_content);
		restaurant.setReg_date(reg_date);
		restaurant.setSearch_loc(search_loc);
		
		RestaurantDBBean restaurant_db = RestaurantDBBean.getInstance();
		restaurant_db.insertArticle(restaurant);
		response.sendRedirect("./cinema_restaurant.jsp");
	} else if(board_id == 4) { //시사회
		String preview_date = multi.getParameter("preview_date");
		String cinema = multi.getParameter("cinema");
		String original_url = multi.getParameter("original_url");
		String preview_region = multi.getParameter("preview_region");
		
		preview.setArticle_title(article_title);
		preview.setPreview_date(preview_date);
		preview.setPreview_region(preview_region);
		preview.setReg_date(reg_date);
		preview.setOriginal_url(original_url);
		preview.setArticle_file(fileName);
		preview.setCinema(cinema);
		
		PreviewDBBean preview_db = PreviewDBBean.getInstance();
		preview_db.insertArticle(preview); 
	    response.sendRedirect("./movie_preview.jsp");
	} else if(board_id == 5) { //영화 이슈
		String original_url = multi.getParameter("original_url");
		
		issue.setArticle_title(article_title);
		issue.setReg_date(reg_date);
		issue.setOriginal_url(original_url);
		issue.setArticle_file(fileName);
		
		IssueDBBean issue_db = IssueDBBean.getInstance();
		issue_db.insertArticle(issue);
		response.sendRedirect("./movie_issue.jsp");
	}


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
